# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 3b9cb130b26d7600deb62a1b35e53b68f18201d985871e91142b50c0b351d1aff3aad22efda4c6348b94340fc3f59067ce5239444c30087248e452ace2e22dd4

test:
  secret_key_base: c1cdbb40dd1a8818cc20cca2748924415f0d2b216538263eaa682e328490682174613ddfb315a7c632eefc906fb44bb05671c5c565f22720191d944710f22c0d

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
